blank_issues_enabled: false
contact_links:
  - name: Features, Bug Reports, Questions
    url: https://github.com/autobrr/qui/discussions/new/choose
    about: Our preferred starting point for questions, suggestions, and contributions.
