// Copyright (c) 2025-2026, s0up and the autobrr contributors.
// SPDX-License-Identifier: GPL-2.0-or-later

package crossseed

import (
	qbt "github.com/autobrr/go-qbittorrent"
	"github.com/moistari/rls"
)

type addPlanLayoutRank int

const (
	addPlanNoAlignment addPlanLayoutRank = iota
	addPlanFilenameAlignment
	addPlanRootAlignment
	addPlanShapeChange
	addPlanRootAndFilenameAlignment
)

type crossSeedAddPlan struct {
	torrent          qbt.Torrent
	files            qbt.TorrentFiles
	sourceFiles      qbt.TorrentFiles
	sourceRelease    *rls.Release
	candidateRelease *rls.Release
	matchType        string
	matchScore       int
	sourceRoot       string
	candidateRoot    string
	contentLayout    string
	// savePathOverride is an explicit save path that pins a rootless single file into the matched folder.
	savePathOverride string
	layoutRank       addPlanLayoutRank
	hasRootFolder    bool
	fileCount        int
	needsRootAlign   bool
	needsFileAlign   bool
	isEpisodeInPack  bool
	forceRecheck     bool
}

func buildCrossSeedAddPlan(
	torrent qbt.Torrent,
	files qbt.TorrentFiles,
	matchType string,
	sourceRelease *rls.Release,
	candidateRelease *rls.Release,
	sourceFiles qbt.TorrentFiles,
) crossSeedAddPlan {
	sourceRoot := detectCommonRoot(sourceFiles)
	candidateRoot := detectCommonRoot(files)
	needsRootAlign := sourceRoot != candidateRoot
	needsFileAlign := filesNeedRenaming(sourceFiles, files)
	sourceHasRoot := sourceRoot != ""
	candidateHasRoot := candidateRoot != ""

	// isEpisodeInPack deliberately keeps contentLayout from becoming "Subfolder"
	// when matchType is partial-in-pack, isTVEpisode(sourceRelease) is true, and
	// isTVSeasonPack(candidateRelease) is true. In that sourceRoot == "" and
	// candidateRoot != "" shape, the episode maps into the season-pack content path
	// instead of a qBittorrent-created subfolder, so classifying it as Subfolder
	// would misrepresent an episode-to-season-pack mapping.
	isEpisodeInPack := (matchType == "partial-in-pack" || matchType == "size-partial-in-pack") &&
		isTVEpisode(sourceRelease) &&
		isTVSeasonPack(candidateRelease)

	// Pick the content layout (and, for rootless single files going into a folder with a name
	// mismatch, the explicit save path) that lands the cross-seed bytes where the matched torrent
	// already stored them.
	contentLayout := "Original"
	savePathOverride := ""
	switch {
	case isEpisodeInPack:
		// maps into the season-pack content path; leave as Original
	case sourceRoot == "" && candidateRoot != "":
		// Derive the matched content FOLDER (not the raw ContentPath): qBittorrent reports the full
		// file path for single-file-in-folder candidates, so use resolveRootlessContentDir to recover
		// the storage directory. If it can't be resolved, fall back to Subfolder to avoid orphaning a
		// bare file inside a path that is actually a file.
		matchedContentDir := resolveRootlessContentDir(&torrent, files)
		if matchedContentDir != "" && rootlessSingleFileNeedsFolderInjection(sourceFiles, candidateRoot, torrent.ContentPath) {
			contentLayout = "Original"
			savePathOverride = matchedContentDir
		} else {
			contentLayout = "Subfolder"
		}
	case sourceRoot != "" && candidateRoot == "":
		contentLayout = "NoSubfolder"
	}

	return crossSeedAddPlan{
		torrent:          torrent,
		files:            files,
		sourceFiles:      sourceFiles,
		sourceRelease:    sourceRelease,
		candidateRelease: candidateRelease,
		matchType:        matchType,
		matchScore:       matchTypePriority(matchType),
		sourceRoot:       sourceRoot,
		candidateRoot:    candidateRoot,
		contentLayout:    contentLayout,
		savePathOverride: savePathOverride,
		layoutRank:       rankAddPlanLayout(sourceHasRoot, candidateHasRoot, needsRootAlign, needsFileAlign),
		hasRootFolder:    candidateHasRoot,
		fileCount:        len(files),
		needsRootAlign:   needsRootAlign,
		needsFileAlign:   needsFileAlign,
		isEpisodeInPack:  isEpisodeInPack,
		forceRecheck:     needsRootAlign || needsFileAlign,
	}
}

// rootlessSingleFileNeedsFolderInjection reports whether a rootless single-file source matched to
// a folder candidate must be pinned into the matched content directory (because the folder
// qBittorrent would auto-generate from the file name differs from the matched folder name).
func rootlessSingleFileNeedsFolderInjection(sourceFiles qbt.TorrentFiles, candidateRoot, matchedContentPath string) bool {
	if matchedContentPath == "" || candidateRoot == "" || len(sourceFiles) != 1 {
		return false
	}
	return autoGeneratedSubfolderName(sourceFiles[0].Name) != candidateRoot
}

func rankAddPlanLayout(sourceHasRoot, candidateHasRoot, needsRootAlign, needsFileAlign bool) addPlanLayoutRank {
	if !needsRootAlign && !needsFileAlign {
		return addPlanNoAlignment
	}

	sameShape := sourceHasRoot == candidateHasRoot
	if sameShape && !needsRootAlign {
		return addPlanFilenameAlignment
	}
	if sameShape && !needsFileAlign {
		return addPlanRootAlignment
	}
	if sameShape {
		return addPlanRootAndFilenameAlignment
	}
	if !needsFileAlign {
		return addPlanShapeChange
	}
	return addPlanRootAndFilenameAlignment
}

func (p crossSeedAddPlan) betterThan(other crossSeedAddPlan, hasOther bool) bool {
	if !hasOther {
		return true
	}
	if p.matchScore != other.matchScore {
		return p.matchScore > other.matchScore
	}
	if p.layoutRank != other.layoutRank {
		return p.layoutRank < other.layoutRank
	}
	if p.hasRootFolder != other.hasRootFolder {
		return p.hasRootFolder
	}
	return p.fileCount > other.fileCount
}
