-- Postgres baseline generated from SQLite v063 schema

CREATE TABLE cross_seed_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    triggered_by TEXT NOT NULL,
    mode TEXT NOT NULL,
    status TEXT NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    total_feed_items INTEGER NOT NULL DEFAULT 0,
    candidates_found INTEGER NOT NULL DEFAULT 0,
    torrents_added INTEGER NOT NULL DEFAULT 0,
    torrents_failed INTEGER NOT NULL DEFAULT 0,
    torrents_skipped INTEGER NOT NULL DEFAULT 0,
    message TEXT,
    error_message TEXT,
    results_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "dashboard_settings" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    section_visibility TEXT NOT NULL DEFAULT '{}',
    section_order TEXT NOT NULL DEFAULT '[]',
    section_collapsed TEXT NOT NULL DEFAULT '{}',
    tracker_breakdown_sort_column TEXT DEFAULT 'uploaded',
    tracker_breakdown_sort_direction TEXT DEFAULT 'desc',
    tracker_breakdown_items_per_page INTEGER DEFAULT 15,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dir_scan_settings (
    id                                 INTEGER PRIMARY KEY CHECK(id = 1),
    enabled                            INTEGER NOT NULL DEFAULT 0,
    match_mode                         TEXT NOT NULL DEFAULT 'strict',
    size_tolerance_percent             REAL NOT NULL DEFAULT 5.0,
    min_piece_ratio                    REAL NOT NULL DEFAULT 0.98,
    allow_partial                      INTEGER NOT NULL DEFAULT 0,
    skip_piece_boundary_safety_check   INTEGER NOT NULL DEFAULT 1,
    start_paused                       INTEGER NOT NULL DEFAULT 1,
    category                           TEXT,
    tags                               TEXT,
    created_at                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    max_searchees_per_run              INTEGER NOT NULL DEFAULT 0,
    max_searchee_age_days              INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE external_programs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    path TEXT NOT NULL,
    args_template TEXT NOT NULL DEFAULT '',
    enabled INTEGER NOT NULL DEFAULT 1,
    use_terminal INTEGER NOT NULL DEFAULT 1,
    path_mappings TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "cross_seed_settings" (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    enabled INTEGER NOT NULL DEFAULT 0,
    run_interval_minutes INTEGER NOT NULL DEFAULT 120,
    start_paused INTEGER NOT NULL DEFAULT 1,
    category TEXT,
    target_instance_ids TEXT NOT NULL DEFAULT '[]',
    target_indexer_ids TEXT NOT NULL DEFAULT '[]',
    max_results_per_run INTEGER NOT NULL DEFAULT 50,
    find_individual_episodes INTEGER NOT NULL DEFAULT 0,
    size_mismatch_tolerance_percent REAL NOT NULL DEFAULT 5.0,
    use_category_from_indexer INTEGER NOT NULL DEFAULT 0,
    run_external_program_id INTEGER REFERENCES external_programs(id) ON DELETE SET NULL,
    rss_automation_tags TEXT NOT NULL DEFAULT '["cross-seed"]',
    seeded_search_tags TEXT NOT NULL DEFAULT '["cross-seed"]',
    completion_search_tags TEXT NOT NULL DEFAULT '["cross-seed"]',
    webhook_tags TEXT NOT NULL DEFAULT '["cross-seed"]',
    inherit_source_tags INTEGER NOT NULL DEFAULT 0,
    use_cross_category_suffix INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    skip_auto_resume_rss INTEGER NOT NULL DEFAULT 0,
    skip_auto_resume_seeded_search INTEGER NOT NULL DEFAULT 0,
    skip_auto_resume_completion INTEGER NOT NULL DEFAULT 0,
    skip_auto_resume_webhook INTEGER NOT NULL DEFAULT 0,
    rss_source_categories TEXT NOT NULL DEFAULT '[]',
    rss_source_tags TEXT NOT NULL DEFAULT '[]',
    rss_source_exclude_categories TEXT NOT NULL DEFAULT '[]',
    rss_source_exclude_tags TEXT NOT NULL DEFAULT '[]',
    webhook_source_categories TEXT NOT NULL DEFAULT '[]',
    webhook_source_tags TEXT NOT NULL DEFAULT '[]',
    webhook_source_exclude_categories TEXT NOT NULL DEFAULT '[]',
    webhook_source_exclude_tags TEXT NOT NULL DEFAULT '[]',
    skip_recheck INTEGER NOT NULL DEFAULT 0,
    skip_piece_boundary_safety_check INTEGER NOT NULL DEFAULT 1,
    use_custom_category INTEGER NOT NULL DEFAULT 0,
    custom_category TEXT DEFAULT '',
    use_cross_category_affix INTEGER NOT NULL DEFAULT 1,
    category_affix_mode TEXT NOT NULL DEFAULT 'suffix',
    category_affix TEXT NOT NULL DEFAULT '.cross',
    gazelle_enabled INTEGER NOT NULL DEFAULT 0,
    redacted_api_key_encrypted TEXT NOT NULL DEFAULT '',
    orpheus_api_key_encrypted TEXT NOT NULL DEFAULT ''
);

CREATE TABLE licenses
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key         TEXT                      not null unique,
    product_name        TEXT                      not null,
    status              TEXT     DEFAULT 'active' not null,
    activated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at          TIMESTAMP,
    last_validated      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    polar_customer_id   TEXT,
    polar_product_id    TEXT,
    polar_activation_id TEXT,
    username            TEXT,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    provider            TEXT,
    dodo_instance_id    TEXT
);

CREATE TABLE log_exclusions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patterns TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notification_targets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    event_types TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
    token TEXT PRIMARY KEY,
    data BYTEA NOT NULL,
    expiry DOUBLE PRECISION NOT NULL
);

CREATE TABLE string_pool (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "api_keys" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_hash TEXT UNIQUE NOT NULL,
    name_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP,
    FOREIGN KEY (name_id) REFERENCES string_pool(id) ON DELETE RESTRICT
);

CREATE TABLE arr_instances (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK(type IN ('sonarr', 'radarr')),
    name_id INTEGER NOT NULL REFERENCES string_pool(id),
    base_url_id INTEGER NOT NULL REFERENCES string_pool(id),
    api_key_encrypted TEXT NOT NULL,
    enabled INTEGER DEFAULT 1,
    priority INTEGER DEFAULT 0,
    timeout_seconds INTEGER DEFAULT 15,
    last_test_at TIMESTAMP,
    last_test_status TEXT DEFAULT 'unknown' CHECK(last_test_status IN ('unknown', 'ok', 'error')),
    last_test_error TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    basic_username_id INTEGER REFERENCES string_pool(id),
    basic_password_encrypted TEXT
);

CREATE TABLE arr_id_cache (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_hash TEXT NOT NULL,
    content_type TEXT NOT NULL CHECK(content_type IN ('movie', 'tv', 'anime', 'unknown')),
    arr_instance_id INTEGER REFERENCES arr_instances(id) ON DELETE SET NULL,
    imdb_id TEXT,
    tmdb_id INTEGER,
    tvdb_id INTEGER,
    tvmaze_id INTEGER,
    titles_json TEXT,
    is_negative INTEGER DEFAULT 0,
    cached_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    UNIQUE(title_hash, content_type)
);

CREATE TABLE instances (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_id INTEGER NOT NULL,
    host_id INTEGER NOT NULL,
    username_id INTEGER NOT NULL,
    password_encrypted TEXT NOT NULL,
    basic_username_id INTEGER,
    basic_password_encrypted TEXT,
    tls_skip_verify INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    has_local_filesystem_access INTEGER NOT NULL DEFAULT 0,
    use_hardlinks INTEGER NOT NULL DEFAULT 0,
    hardlink_base_dir TEXT NOT NULL DEFAULT '',
    hardlink_dir_preset TEXT NOT NULL DEFAULT 'flat',
    use_reflinks INTEGER NOT NULL DEFAULT 0,
    fallback_to_regular_mode INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (name_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (host_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (username_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (basic_username_id) REFERENCES string_pool(id) ON DELETE RESTRICT
);

CREATE TABLE automation_activity (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id     INTEGER NOT NULL,
    hash            TEXT NOT NULL,
    torrent_name    TEXT,
    tracker_domain  TEXT,
    action          TEXT NOT NULL,
    rule_id         INTEGER,
    rule_name       TEXT,
    outcome         TEXT NOT NULL,
    reason          TEXT,
    details         TEXT,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
);

CREATE TABLE automations (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id     INTEGER NOT NULL,
    name            TEXT NOT NULL,
    tracker_pattern TEXT NOT NULL,
    conditions      TEXT NOT NULL,
    enabled         INTEGER NOT NULL DEFAULT 1,
    sort_order      INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    interval_seconds INTEGER,
    free_space_source TEXT,
    dry_run INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
);

CREATE TABLE client_api_keys (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_hash TEXT NOT NULL UNIQUE,
    client_name_id INTEGER NOT NULL,
    instance_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP,
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE,
    FOREIGN KEY (client_name_id) REFERENCES string_pool(id) ON DELETE RESTRICT
);

CREATE TABLE cross_seed_blocklist (
    instance_id INTEGER NOT NULL,
    infohash TEXT NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (instance_id, infohash),
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
);

CREATE TABLE cross_seed_search_history (
    instance_id INTEGER NOT NULL,
    torrent_hash TEXT NOT NULL,
    last_searched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (instance_id, torrent_hash),
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
);

CREATE TABLE cross_seed_search_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id INTEGER NOT NULL,
    status TEXT NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    total_torrents INTEGER NOT NULL DEFAULT 0,
    processed INTEGER NOT NULL DEFAULT 0,
    torrents_added INTEGER NOT NULL DEFAULT 0,
    torrents_failed INTEGER NOT NULL DEFAULT 0,
    torrents_skipped INTEGER NOT NULL DEFAULT 0,
    message TEXT,
    error_message TEXT,
    filters_json TEXT,
    indexer_ids_json TEXT,
    interval_seconds INTEGER NOT NULL DEFAULT 60,
    cooldown_minutes INTEGER NOT NULL DEFAULT 360,
    results_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
);

CREATE TABLE cross_seed_search_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    instance_id INTEGER,
    categories TEXT NOT NULL DEFAULT '[]',
    tags TEXT NOT NULL DEFAULT '[]',
    indexer_ids TEXT NOT NULL DEFAULT '[]',
    interval_seconds INTEGER NOT NULL DEFAULT 60,
    cooldown_minutes INTEGER NOT NULL DEFAULT 720,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE SET NULL
);

CREATE TABLE dir_scan_directories (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path                     TEXT NOT NULL,
    qbit_path_prefix         TEXT,
    enabled                  INTEGER NOT NULL DEFAULT 1,
    arr_instance_id          INTEGER REFERENCES arr_instances(id) ON DELETE SET NULL,
    target_instance_id       INTEGER NOT NULL REFERENCES instances(id) ON DELETE CASCADE,
    scan_interval_minutes    INTEGER NOT NULL DEFAULT 1440,
    last_scan_at             TIMESTAMP,
    category                 TEXT,
    tags                     TEXT,
    created_at               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dir_scan_files (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    directory_id         INTEGER NOT NULL REFERENCES dir_scan_directories(id) ON DELETE CASCADE,
    file_path            TEXT NOT NULL,
    file_size            BIGINT NOT NULL,
    file_mod_time        TIMESTAMP NOT NULL,
    file_id              BYTEA,
    status               TEXT NOT NULL DEFAULT 'pending',
    matched_torrent_hash TEXT,
    matched_indexer_id   INTEGER,
    last_processed_at    TIMESTAMP,
    UNIQUE(directory_id, file_path)
);

CREATE TABLE dir_scan_runs (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    directory_id     INTEGER NOT NULL REFERENCES dir_scan_directories(id) ON DELETE CASCADE,
    status           TEXT NOT NULL,
    triggered_by     TEXT NOT NULL,
    files_found      INTEGER NOT NULL DEFAULT 0,
    files_skipped    INTEGER NOT NULL DEFAULT 0,
    matches_found    INTEGER NOT NULL DEFAULT 0,
    torrents_added   INTEGER NOT NULL DEFAULT 0,
    error_message    TEXT,
    started_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at     TIMESTAMP
);

CREATE TABLE dir_scan_run_injections (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                INTEGER NOT NULL REFERENCES dir_scan_runs(id) ON DELETE CASCADE,
    directory_id          INTEGER NOT NULL REFERENCES dir_scan_directories(id) ON DELETE CASCADE,
    status                TEXT NOT NULL, -- added | failed
    searchee_name         TEXT NOT NULL,
    torrent_name          TEXT NOT NULL,
    info_hash             TEXT NOT NULL,
    content_type          TEXT NOT NULL, -- movie | tv
    indexer_name          TEXT,
    tracker_domain        TEXT,
    tracker_display_name  TEXT,
    link_mode             TEXT,
    save_path             TEXT,
    category              TEXT,
    tags                  TEXT, -- JSON array
    error_message         TEXT,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE instance_backup_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id INTEGER NOT NULL,
    kind_id INTEGER NOT NULL,
    status_id INTEGER NOT NULL,
    requested_by_id INTEGER NOT NULL,
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    archive_path_id INTEGER,
    manifest_path_id INTEGER,
    total_bytes BIGINT NOT NULL DEFAULT 0,
    torrent_count INTEGER NOT NULL DEFAULT 0,
    category_counts_json TEXT,
    categories_json TEXT,
    tags_json TEXT,
    error_message_id INTEGER,
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE,
    FOREIGN KEY (kind_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (status_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (requested_by_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (error_message_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (archive_path_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (manifest_path_id) REFERENCES string_pool(id) ON DELETE RESTRICT
);

CREATE TABLE instance_backup_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id INTEGER NOT NULL,
    torrent_hash_id INTEGER NOT NULL,
    name_id INTEGER NOT NULL,
    category_id INTEGER,
    size_bytes BIGINT NOT NULL,
    archive_rel_path_id INTEGER,
    infohash_v1_id INTEGER,
    infohash_v2_id INTEGER,
    tags_id INTEGER,
    torrent_blob_path_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (run_id) REFERENCES instance_backup_runs(id) ON DELETE CASCADE,
    FOREIGN KEY (torrent_hash_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (name_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (category_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (tags_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (archive_rel_path_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (infohash_v1_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (infohash_v2_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (torrent_blob_path_id) REFERENCES string_pool(id) ON DELETE RESTRICT
);

CREATE TABLE instance_backup_settings (
    instance_id INTEGER PRIMARY KEY,
    enabled INTEGER NOT NULL DEFAULT 0,
    hourly_enabled INTEGER NOT NULL DEFAULT 0,
    daily_enabled INTEGER NOT NULL DEFAULT 0,
    weekly_enabled INTEGER NOT NULL DEFAULT 0,
    monthly_enabled INTEGER NOT NULL DEFAULT 0,
    keep_hourly INTEGER NOT NULL DEFAULT 0,
    keep_daily INTEGER NOT NULL DEFAULT 7,
    keep_weekly INTEGER NOT NULL DEFAULT 4,
    keep_monthly INTEGER NOT NULL DEFAULT 12,
    include_categories INTEGER NOT NULL DEFAULT 1,
    include_tags INTEGER NOT NULL DEFAULT 1,
    custom_path TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
);

CREATE TABLE instance_crossseed_completion_settings (
    instance_id INTEGER PRIMARY KEY REFERENCES instances(id) ON DELETE CASCADE,
    enabled INTEGER NOT NULL DEFAULT 0,
    categories_json TEXT NOT NULL DEFAULT '[]',
    tags_json TEXT NOT NULL DEFAULT '[]',
    exclude_categories_json TEXT NOT NULL DEFAULT '[]',
    exclude_tags_json TEXT NOT NULL DEFAULT '[]',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    indexer_ids_json TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE instance_errors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id INTEGER NOT NULL,
    error_type_id INTEGER NOT NULL,
    error_message_id INTEGER NOT NULL,
    occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE,
    FOREIGN KEY (error_type_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (error_message_id) REFERENCES string_pool(id) ON DELETE RESTRICT
);

CREATE TABLE instance_reannounce_settings (
    instance_id INTEGER PRIMARY KEY REFERENCES instances(id) ON DELETE CASCADE,
    enabled INTEGER NOT NULL DEFAULT 0,
    initial_wait_seconds INTEGER NOT NULL DEFAULT 15,
    reannounce_interval_seconds INTEGER NOT NULL DEFAULT 7,
    max_age_seconds INTEGER NOT NULL DEFAULT 600,
    aggressive INTEGER NOT NULL DEFAULT 0,
    monitor_all INTEGER NOT NULL DEFAULT 1,
    exclude_categories INTEGER NOT NULL DEFAULT 0,
    categories_json TEXT NOT NULL DEFAULT '[]',
    exclude_tags INTEGER NOT NULL DEFAULT 0,
    tags_json TEXT NOT NULL DEFAULT '[]',
    exclude_trackers INTEGER NOT NULL DEFAULT 0,
    trackers_json TEXT NOT NULL DEFAULT '[]',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    max_retries INTEGER NOT NULL DEFAULT 50
);

CREATE TABLE orphan_scan_runs (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id     INTEGER NOT NULL,
    status          TEXT NOT NULL,
    triggered_by    TEXT NOT NULL,
    scan_paths      TEXT,
    files_found     INTEGER DEFAULT 0,
    files_deleted   INTEGER DEFAULT 0,
    folders_deleted INTEGER DEFAULT 0,
    bytes_reclaimed BIGINT DEFAULT 0,
    truncated       INTEGER NOT NULL DEFAULT 0,
    error_message   TEXT,
    started_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMP,
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
);

CREATE TABLE orphan_scan_files (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        INTEGER NOT NULL,
    file_path     TEXT NOT NULL,
    file_size     BIGINT NOT NULL,
    modified_at   TIMESTAMP,
    status        TEXT NOT NULL DEFAULT 'pending',
    error_message TEXT,
    FOREIGN KEY (run_id) REFERENCES orphan_scan_runs(id) ON DELETE CASCADE
);

CREATE TABLE orphan_scan_settings (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id           INTEGER NOT NULL UNIQUE,
    enabled               INTEGER NOT NULL DEFAULT 0,
    grace_period_minutes  INTEGER NOT NULL DEFAULT 10,
    ignore_paths          TEXT,
    scan_interval_hours   INTEGER NOT NULL DEFAULT 24,
    max_files_per_run     INTEGER NOT NULL DEFAULT 10000,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    auto_cleanup_enabled INTEGER NOT NULL DEFAULT 0,
    auto_cleanup_max_files INTEGER NOT NULL DEFAULT 100,
    preview_sort TEXT NOT NULL DEFAULT 'size_desc',
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
);

CREATE TABLE torrent_files_cache (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id INTEGER NOT NULL,
    torrent_hash_id INTEGER NOT NULL,
    file_index INTEGER NOT NULL,
    name_id INTEGER NOT NULL,
    size BIGINT NOT NULL,
    progress REAL NOT NULL,
    priority INTEGER NOT NULL,
    is_seed INTEGER,
    piece_range_start INTEGER,
    piece_range_end INTEGER,
    availability REAL NOT NULL,
    cached_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE,
    FOREIGN KEY (torrent_hash_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    FOREIGN KEY (name_id) REFERENCES string_pool(id) ON DELETE RESTRICT,
    UNIQUE(instance_id, torrent_hash_id, file_index)
);

CREATE TABLE torrent_files_sync (
    instance_id INTEGER NOT NULL,
    torrent_hash_id INTEGER NOT NULL,
    last_synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    torrent_progress REAL NOT NULL DEFAULT 0,
    file_count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (instance_id, torrent_hash_id),
    FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE,
    FOREIGN KEY (torrent_hash_id) REFERENCES string_pool(id) ON DELETE RESTRICT
);

CREATE TABLE torznab_indexers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_id INTEGER NOT NULL REFERENCES string_pool(id),
    base_url_id INTEGER NOT NULL REFERENCES string_pool(id),
    indexer_id_string_id INTEGER REFERENCES string_pool(id),
    api_key_encrypted TEXT NOT NULL,
    backend TEXT NOT NULL DEFAULT 'jackett' CHECK(backend IN ('jackett', 'prowlarr', 'native')),
    enabled INTEGER DEFAULT 1,
    priority INTEGER DEFAULT 0,
    timeout_seconds INTEGER DEFAULT 30,
    capabilities TEXT DEFAULT '[]',
    last_test_at TIMESTAMP,
    last_test_status TEXT DEFAULT 'unknown' CHECK(last_test_status IN ('unknown', 'ok', 'error')),
    last_test_error TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    limit_default INTEGER NOT NULL DEFAULT 100,
    limit_max INTEGER NOT NULL DEFAULT 100,
    basic_username_id INTEGER REFERENCES string_pool(id),
    basic_password_encrypted TEXT
);

CREATE TABLE cross_seed_feed_items (
    guid TEXT NOT NULL,
    indexer_id INTEGER NOT NULL,
    title TEXT,
    first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_status TEXT NOT NULL DEFAULT 'pending',
    last_run_id INTEGER,
    info_hash TEXT,
    PRIMARY KEY (guid, indexer_id),
    FOREIGN KEY (indexer_id) REFERENCES torznab_indexers(id) ON DELETE CASCADE,
    FOREIGN KEY (last_run_id) REFERENCES cross_seed_runs(id) ON DELETE SET NULL
);

CREATE TABLE torznab_indexer_capabilities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indexer_id INTEGER NOT NULL REFERENCES torznab_indexers(id) ON DELETE CASCADE,
    capability_type_id INTEGER NOT NULL REFERENCES string_pool(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(indexer_id, capability_type_id)
);

CREATE TABLE torznab_indexer_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indexer_id INTEGER NOT NULL REFERENCES torznab_indexers(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL,
    category_name_id INTEGER NOT NULL REFERENCES string_pool(id),
    parent_category_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(indexer_id, category_id)
);

CREATE TABLE torznab_indexer_cooldowns (
    indexer_id INTEGER PRIMARY KEY REFERENCES torznab_indexers(id) ON DELETE CASCADE,
    resume_at TIMESTAMP NOT NULL,
    cooldown_seconds INTEGER NOT NULL,
    reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE torznab_indexer_errors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indexer_id INTEGER NOT NULL REFERENCES torznab_indexers(id) ON DELETE CASCADE,
    error_message_id INTEGER NOT NULL REFERENCES string_pool(id),
    error_code TEXT,
    occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    error_count INTEGER DEFAULT 1
);

CREATE TABLE torznab_indexer_latency (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indexer_id INTEGER NOT NULL REFERENCES torznab_indexers(id) ON DELETE CASCADE,
    operation_type TEXT NOT NULL,
    latency_ms INTEGER NOT NULL,
    success INTEGER NOT NULL,
    measured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE torznab_search_cache (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key TEXT NOT NULL UNIQUE,
    scope TEXT NOT NULL DEFAULT 'generic',
    query TEXT,
    categories_json TEXT,
    indexer_ids_json TEXT,
    indexer_matcher TEXT NOT NULL DEFAULT '',
    request_fingerprint TEXT NOT NULL,
    response_data BYTEA NOT NULL,
    total_results INTEGER NOT NULL DEFAULT 0,
    cached_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    hit_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE torznab_search_cache_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    ttl_minutes INTEGER NOT NULL DEFAULT 1440,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE torznab_torrent_cache (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indexer_id INTEGER NOT NULL REFERENCES torznab_indexers(id) ON DELETE CASCADE,
    cache_key TEXT NOT NULL,
    guid TEXT,
    download_url TEXT,
    info_hash TEXT,
    title TEXT,
    size_bytes BIGINT,
    torrent_data BYTEA NOT NULL,
    cached_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(indexer_id, cache_key)
);

CREATE TABLE tracker_customizations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name TEXT NOT NULL,
    domains TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    included_in_stats TEXT DEFAULT ''
);

CREATE TABLE "user" (
    id INTEGER PRIMARY KEY CHECK (id = 1), -- Ensures only one user
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_arr_id_cache_expires ON arr_id_cache(expires_at);

CREATE INDEX idx_arr_id_cache_instance ON arr_id_cache(arr_instance_id);

CREATE INDEX idx_arr_id_cache_lookup ON arr_id_cache(title_hash, content_type);

CREATE INDEX idx_arr_instances_base_url_id ON arr_instances(base_url_id);

CREATE INDEX idx_arr_instances_enabled ON arr_instances(enabled);

CREATE INDEX idx_arr_instances_name_id ON arr_instances(name_id);

CREATE INDEX idx_arr_instances_priority ON arr_instances(type, enabled, priority DESC);

CREATE INDEX idx_arr_instances_type ON arr_instances(type);

CREATE UNIQUE INDEX idx_arr_instances_type_base_url ON arr_instances(type, base_url_id);

CREATE INDEX idx_automation_activity_instance_created
    ON automation_activity(instance_id, created_at DESC);

CREATE INDEX idx_automations_instance ON automations(instance_id, sort_order, id);

CREATE INDEX idx_backup_items_hash ON instance_backup_items(torrent_hash_id);

CREATE INDEX idx_backup_items_run ON instance_backup_items(run_id);

CREATE INDEX idx_client_api_keys_instance_id ON client_api_keys(instance_id);

CREATE INDEX idx_cross_seed_blocklist_instance
    ON cross_seed_blocklist(instance_id, created_at DESC);

CREATE INDEX idx_cross_seed_feed_items_indexer ON cross_seed_feed_items(indexer_id);

CREATE INDEX idx_cross_seed_feed_items_last_seen ON cross_seed_feed_items(last_seen_at DESC);

CREATE INDEX idx_cross_seed_runs_started_at ON cross_seed_runs(started_at DESC);

CREATE INDEX idx_cross_seed_search_history_last ON cross_seed_search_history(last_searched_at);

CREATE INDEX idx_cross_seed_search_runs_instance
    ON cross_seed_search_runs(instance_id, started_at DESC);

CREATE INDEX idx_dir_scan_files_directory
    ON dir_scan_files(directory_id);

CREATE INDEX idx_dir_scan_files_fileid
    ON dir_scan_files(directory_id, file_id)
    WHERE file_id IS NOT NULL;

CREATE INDEX idx_dir_scan_run_injections_directory_created
    ON dir_scan_run_injections(directory_id, created_at DESC);

CREATE INDEX idx_dir_scan_run_injections_run_created
    ON dir_scan_run_injections(run_id, created_at DESC);

CREATE INDEX idx_dir_scan_runs_directory_started
    ON dir_scan_runs(directory_id, started_at DESC);

CREATE INDEX idx_external_programs_enabled ON external_programs(enabled);

CREATE INDEX idx_instance_backup_runs_instance ON instance_backup_runs(instance_id, requested_at DESC);

CREATE INDEX idx_instance_errors_lookup ON instance_errors(instance_id, occurred_at DESC);

CREATE INDEX idx_instances_is_active ON instances(is_active, id);

CREATE INDEX idx_instances_sort_order ON instances(sort_order, id);

CREATE INDEX idx_licenses_key ON licenses(license_key);

CREATE INDEX idx_licenses_status ON licenses(status);

CREATE INDEX idx_licenses_theme ON licenses(product_name);

CREATE INDEX idx_notification_targets_enabled ON notification_targets(enabled);

CREATE INDEX idx_orphan_scan_files_run ON orphan_scan_files(run_id);

CREATE INDEX idx_orphan_scan_runs_instance_started
    ON orphan_scan_runs(instance_id, started_at DESC);

CREATE INDEX idx_torrent_files_cache_cached_at ON torrent_files_cache(cached_at);

CREATE INDEX idx_torrent_files_cache_lookup ON torrent_files_cache(instance_id, torrent_hash_id);

CREATE INDEX idx_torrent_files_sync_last_synced ON torrent_files_sync(last_synced_at);

CREATE INDEX idx_torznab_capabilities_indexer ON torznab_indexer_capabilities(indexer_id);

CREATE INDEX idx_torznab_capabilities_type ON torznab_indexer_capabilities(capability_type_id);

CREATE INDEX idx_torznab_categories_category_id ON torznab_indexer_categories(category_id);

CREATE INDEX idx_torznab_categories_indexer ON torznab_indexer_categories(indexer_id);

CREATE INDEX idx_torznab_categories_parent ON torznab_indexer_categories(parent_category_id);

CREATE INDEX idx_torznab_cooldowns_resume
    ON torznab_indexer_cooldowns(resume_at);

CREATE INDEX idx_torznab_errors_indexer ON torznab_indexer_errors(indexer_id);

CREATE INDEX idx_torznab_errors_occurred ON torznab_indexer_errors(occurred_at DESC);

CREATE INDEX idx_torznab_errors_unresolved ON torznab_indexer_errors(indexer_id, resolved_at) WHERE resolved_at IS NULL;

CREATE INDEX idx_torznab_indexers_base_url_id ON torznab_indexers(base_url_id);

CREATE INDEX idx_torznab_indexers_enabled ON torznab_indexers(enabled);

CREATE INDEX idx_torznab_indexers_indexer_id ON torznab_indexers(indexer_id_string_id);

CREATE INDEX idx_torznab_indexers_name_id ON torznab_indexers(name_id);

CREATE INDEX idx_torznab_indexers_priority ON torznab_indexers(priority DESC);

CREATE INDEX idx_torznab_latency_indexer ON torznab_indexer_latency(indexer_id);

CREATE INDEX idx_torznab_latency_measured ON torznab_indexer_latency(measured_at DESC);

CREATE INDEX idx_torznab_latency_operation ON torznab_indexer_latency(indexer_id, operation_type, measured_at DESC);

CREATE INDEX idx_torznab_search_cache_expires ON torznab_search_cache(expires_at);

CREATE INDEX idx_torznab_search_cache_matcher ON torznab_search_cache(indexer_matcher);

CREATE INDEX idx_torznab_search_cache_scope ON torznab_search_cache(scope);

CREATE INDEX idx_torznab_torrent_cache_cache_key ON torznab_torrent_cache(indexer_id, cache_key);

CREATE INDEX idx_torznab_torrent_cache_last_used ON torznab_torrent_cache(last_used_at);

CREATE INDEX idx_tracker_customizations_domains ON tracker_customizations(domains);

CREATE INDEX sessions_expiry_idx ON sessions(expiry);

CREATE VIEW api_keys_view AS
SELECT
    ak.id,
    ak.key_hash,
    sp.value AS name,
    ak.created_at,
    ak.last_used_at
FROM api_keys ak
INNER JOIN string_pool sp ON ak.name_id = sp.id;

CREATE VIEW arr_instances_view AS
SELECT
    ai.id,
    ai.type,
    sp_name.value AS name,
    sp_base_url.value AS base_url,
    sp_basic_user.value AS basic_username,
    ai.basic_password_encrypted,
    ai.api_key_encrypted,
    ai.enabled,
    ai.priority,
    ai.timeout_seconds,
    ai.last_test_at,
    ai.last_test_status,
    ai.last_test_error,
    ai.created_at,
    ai.updated_at
FROM arr_instances ai
INNER JOIN string_pool sp_name ON ai.name_id = sp_name.id
INNER JOIN string_pool sp_base_url ON ai.base_url_id = sp_base_url.id
LEFT JOIN string_pool sp_basic_user ON ai.basic_username_id = sp_basic_user.id;

CREATE VIEW client_api_keys_view AS
SELECT
    cak.id,
    cak.key_hash,
    sp.value AS client_name,
    cak.instance_id,
    cak.created_at,
    cak.last_used_at
FROM client_api_keys cak
INNER JOIN string_pool sp ON cak.client_name_id = sp.id;

CREATE VIEW instance_backup_items_view AS
SELECT
    ibi.id,
    ibi.run_id,
    sp_hash.value as torrent_hash,
    sp_name.value as name,
    sp_cat.value as category,
    ibi.size_bytes,
    sp_archive.value as archive_rel_path,
    sp_infohash_v1.value as infohash_v1,
    sp_infohash_v2.value as infohash_v2,
    sp_tags.value as tags,
    sp_blob.value as torrent_blob_path,
    ibi.created_at
FROM instance_backup_items ibi
LEFT JOIN string_pool sp_hash ON ibi.torrent_hash_id = sp_hash.id
LEFT JOIN string_pool sp_name ON ibi.name_id = sp_name.id
LEFT JOIN string_pool sp_cat ON ibi.category_id = sp_cat.id
LEFT JOIN string_pool sp_archive ON ibi.archive_rel_path_id = sp_archive.id
LEFT JOIN string_pool sp_infohash_v1 ON ibi.infohash_v1_id = sp_infohash_v1.id
LEFT JOIN string_pool sp_infohash_v2 ON ibi.infohash_v2_id = sp_infohash_v2.id
LEFT JOIN string_pool sp_tags ON ibi.tags_id = sp_tags.id
LEFT JOIN string_pool sp_blob ON ibi.torrent_blob_path_id = sp_blob.id;

CREATE VIEW instance_backup_runs_view AS
SELECT
    ibr.id,
    ibr.instance_id,
    sp_kind.value AS kind,
    sp_status.value AS status,
    sp_requested_by.value AS requested_by,
    ibr.requested_at,
    ibr.started_at,
    ibr.completed_at,
    sp_archive.value AS archive_path,
    sp_manifest.value AS manifest_path,
    ibr.total_bytes,
    ibr.torrent_count,
    ibr.category_counts_json,
    ibr.categories_json,
    ibr.tags_json,
    sp_error.value AS error_message
FROM instance_backup_runs ibr
JOIN string_pool sp_kind ON ibr.kind_id = sp_kind.id
JOIN string_pool sp_status ON ibr.status_id = sp_status.id
JOIN string_pool sp_requested_by ON ibr.requested_by_id = sp_requested_by.id
LEFT JOIN string_pool sp_error ON ibr.error_message_id = sp_error.id
LEFT JOIN string_pool sp_archive ON ibr.archive_path_id = sp_archive.id
LEFT JOIN string_pool sp_manifest ON ibr.manifest_path_id = sp_manifest.id;

CREATE VIEW instance_errors_view AS
SELECT
    ie.id,
    ie.instance_id,
    ie.error_type_id,
    sp_type.value AS error_type,
    ie.error_message_id,
    sp_message.value AS error_message,
    ie.occurred_at
FROM instance_errors ie
LEFT JOIN string_pool sp_type ON ie.error_type_id = sp_type.id
LEFT JOIN string_pool sp_message ON ie.error_message_id = sp_message.id;

CREATE VIEW instances_view AS
SELECT
    i.id,
    n.value AS name,
    h.value AS host,
    u.value AS username,
    i.password_encrypted,
    bu.value AS basic_username,
    i.basic_password_encrypted,
    i.tls_skip_verify,
    i.sort_order,
    i.is_active,
    i.has_local_filesystem_access,
    i.use_hardlinks,
    i.hardlink_base_dir,
    i.hardlink_dir_preset,
    i.use_reflinks,
    i.fallback_to_regular_mode
FROM instances i
LEFT JOIN string_pool n ON i.name_id = n.id
LEFT JOIN string_pool h ON i.host_id = h.id
LEFT JOIN string_pool u ON i.username_id = u.id
LEFT JOIN string_pool bu ON i.basic_username_id = bu.id;

CREATE VIEW torrent_files_cache_view AS
SELECT
    tfc.id,
    tfc.instance_id,
    tfc.torrent_hash_id,
    sp_hash.value AS torrent_hash,
    tfc.file_index,
    tfc.name_id,
    sp_name.value AS name,
    tfc.size,
    tfc.progress,
    tfc.priority,
    tfc.is_seed,
    tfc.piece_range_start,
    tfc.piece_range_end,
    tfc.availability,
    tfc.cached_at
FROM torrent_files_cache tfc
LEFT JOIN string_pool sp_hash ON tfc.torrent_hash_id = sp_hash.id
LEFT JOIN string_pool sp_name ON tfc.name_id = sp_name.id;

CREATE VIEW torrent_files_sync_view AS
SELECT
    tfs.instance_id,
    tfs.torrent_hash_id,
    sp_hash.value AS torrent_hash,
    tfs.last_synced_at,
    tfs.torrent_progress,
    tfs.file_count
FROM torrent_files_sync tfs
LEFT JOIN string_pool sp_hash ON tfs.torrent_hash_id = sp_hash.id;

CREATE VIEW torznab_indexer_capabilities_view AS
SELECT
    tic.indexer_id,
    sp.value AS capability_type
FROM torznab_indexer_capabilities tic
INNER JOIN string_pool sp ON tic.capability_type_id = sp.id;

CREATE VIEW torznab_indexer_categories_view AS
SELECT
    tcat.indexer_id,
    tcat.category_id,
    sp.value AS category_name,
    tcat.parent_category_id
FROM torznab_indexer_categories tcat
INNER JOIN string_pool sp ON tcat.category_name_id = sp.id;

CREATE VIEW torznab_indexer_health AS
SELECT
    ti.id AS indexer_id,
    sp_name.value AS indexer_name,
    ti.enabled,
    ti.last_test_status,
    COALESCE(err_recent.error_count, 0) AS errors_last_24h,
    COALESCE(err_unresolved.unresolved_count, 0) AS unresolved_errors,
    lat.avg_latency_ms,
    lat.success_rate_pct,
    lat.total_requests AS requests_last_7d,
    lat.last_measured_at
FROM torznab_indexers ti
INNER JOIN string_pool sp_name ON ti.name_id = sp_name.id
LEFT JOIN (
    SELECT indexer_id, COUNT(*) AS error_count
    FROM torznab_indexer_errors
    WHERE occurred_at > CURRENT_TIMESTAMP - INTERVAL '1 day'
    GROUP BY indexer_id
) err_recent ON ti.id = err_recent.indexer_id
LEFT JOIN (
    SELECT indexer_id, COUNT(*) AS unresolved_count
    FROM torznab_indexer_errors
    WHERE resolved_at IS NULL
    GROUP BY indexer_id
) err_unresolved ON ti.id = err_unresolved.indexer_id
LEFT JOIN (
    SELECT
        indexer_id,
        AVG(CASE WHEN success = 1 THEN latency_ms ELSE NULL END) AS avg_latency_ms,
        CAST(SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) * 100 AS success_rate_pct,
        COUNT(*) AS total_requests,
        MAX(measured_at) AS last_measured_at
    FROM torznab_indexer_latency
    WHERE measured_at > CURRENT_TIMESTAMP - INTERVAL '7 days'
    GROUP BY indexer_id
) lat ON ti.id = lat.indexer_id;

CREATE VIEW torznab_indexer_latency_stats AS
SELECT
    indexer_id,
    operation_type,
    COUNT(*) AS total_requests,
    SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) AS successful_requests,
    AVG(CASE WHEN success = 1 THEN latency_ms ELSE NULL END) AS avg_latency_ms,
    MIN(CASE WHEN success = 1 THEN latency_ms ELSE NULL END) AS min_latency_ms,
    MAX(CASE WHEN success = 1 THEN latency_ms ELSE NULL END) AS max_latency_ms,
    CAST(SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) * 100 AS success_rate_pct,
    MAX(measured_at) AS last_measured_at
FROM torznab_indexer_latency
WHERE measured_at > CURRENT_TIMESTAMP - INTERVAL '7 days'
GROUP BY indexer_id, operation_type;

CREATE VIEW torznab_indexers_view AS
SELECT
    ti.id,
    sp_name.value AS name,
    sp_base_url.value AS base_url,
    sp_indexer_id.value AS indexer_id,
    sp_basic_user.value AS basic_username,
    ti.basic_password_encrypted,
    ti.backend,
    ti.api_key_encrypted,
    ti.enabled,
    ti.priority,
    ti.timeout_seconds,
    ti.limit_default,
    ti.limit_max,
    ti.last_test_at,
    ti.last_test_status,
    ti.last_test_error,
    ti.created_at,
    ti.updated_at
FROM torznab_indexers ti
INNER JOIN string_pool sp_name ON ti.name_id = sp_name.id
INNER JOIN string_pool sp_base_url ON ti.base_url_id = sp_base_url.id
LEFT JOIN string_pool sp_indexer_id ON ti.indexer_id_string_id = sp_indexer_id.id
LEFT JOIN string_pool sp_basic_user ON ti.basic_username_id = sp_basic_user.id;

INSERT INTO string_pool (value) VALUES ('') ON CONFLICT(value) DO NOTHING;
INSERT INTO torznab_search_cache_settings (id, ttl_minutes) VALUES (1, 1440) ON CONFLICT(id) DO NOTHING;
INSERT INTO dir_scan_settings (id) VALUES (1) ON CONFLICT(id) DO NOTHING;
