-- Season pack settings on cross_seed_settings table.
ALTER TABLE cross_seed_settings ADD COLUMN season_pack_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cross_seed_settings ADD COLUMN season_pack_coverage_threshold REAL NOT NULL DEFAULT 0.75;
ALTER TABLE cross_seed_settings ADD COLUMN season_pack_skip_repack_compare INTEGER NOT NULL DEFAULT 1;
ALTER TABLE cross_seed_settings ADD COLUMN season_pack_simplify_hdr_compare INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cross_seed_settings ADD COLUMN season_pack_simplify_web_compare INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cross_seed_settings ADD COLUMN season_pack_skip_year_compare INTEGER NOT NULL DEFAULT 0;

-- Season pack run activity table.
CREATE TABLE season_pack_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    torrent_name TEXT NOT NULL,
    phase TEXT NOT NULL,
    status TEXT NOT NULL,
    reason TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL DEFAULT '',
    instance_id INTEGER,
    matched_episodes INTEGER NOT NULL DEFAULT 0,
    total_episodes INTEGER NOT NULL DEFAULT 0,
    coverage REAL NOT NULL DEFAULT 0,
    link_mode TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE cross_seed_settings ADD COLUMN season_pack_tags TEXT NOT NULL DEFAULT '["cross-seed"]';
ALTER TABLE cross_seed_settings ADD COLUMN season_pack_tvdb_api_key_encrypted TEXT NOT NULL DEFAULT '';
ALTER TABLE cross_seed_settings ADD COLUMN season_pack_tvdb_pin_encrypted TEXT NOT NULL DEFAULT '';
