-- Copyright (c) 2025-2026, s0up and the autobrr contributors.
-- SPDX-License-Identifier: GPL-2.0-or-later

-- Widen int4 identity and string_pool FK columns to BIGINT.
--
-- string_pool.id was INTEGER GENERATED BY DEFAULT AS IDENTITY (int4, max
-- 2147483647). Interning runs INSERT ... ON CONFLICT DO NOTHING, and Postgres
-- evaluates nextval before conflict detection, so re-interning existing
-- strings permanently consumes sequence values. High-frequency re-interning
-- (file cache refreshes) exhausts the int4 sequence even though the table
-- stays small, after which every string_pool insert fails with SQLSTATE 2200H.
-- The other identity columns below burn the same way via ON CONFLICT upserts.
--
-- ALTER COLUMN TYPE BIGINT on an identity column automatically retypes the
-- backing sequence to bigint and lifts its MAXVALUE (the old MAXVALUE equaled
-- the int4 type max). FK columns must be widened too: an int4 column cannot
-- store ids above 2147483647.
--
-- Postgres cannot ALTER COLUMN TYPE while dependent views exist, so all views
-- referencing string_pool or the widened columns are dropped and recreated
-- from their current definitions (063 baseline, except instance_backup_items_view,
-- instance_backup_runs_view and torrent_files_cache_view from 064, and
-- instances_view from 075). SQLite needs no counterpart: its INTEGER PRIMARY
-- KEY ids are already 64-bit.

DROP VIEW IF EXISTS api_keys_view;
DROP VIEW IF EXISTS arr_instances_view;
DROP VIEW IF EXISTS client_api_keys_view;
DROP VIEW IF EXISTS instance_backup_items_view;
DROP VIEW IF EXISTS instance_backup_runs_view;
DROP VIEW IF EXISTS instance_errors_view;
DROP VIEW IF EXISTS instances_view;
DROP VIEW IF EXISTS torrent_files_cache_view;
DROP VIEW IF EXISTS torrent_files_sync_view;
DROP VIEW IF EXISTS torznab_indexer_capabilities_view;
DROP VIEW IF EXISTS torznab_indexer_categories_view;
DROP VIEW IF EXISTS torznab_indexer_health;
DROP VIEW IF EXISTS torznab_indexers_view;

ALTER TABLE string_pool
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE arr_id_cache
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE torznab_torrent_cache
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE torznab_search_cache
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE dir_scan_files
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE torrent_files_cache
    ALTER COLUMN id TYPE BIGINT,
    ALTER COLUMN torrent_hash_id TYPE BIGINT,
    ALTER COLUMN name_id TYPE BIGINT;

ALTER TABLE api_keys
    ALTER COLUMN name_id TYPE BIGINT;

ALTER TABLE arr_instances
    ALTER COLUMN name_id TYPE BIGINT,
    ALTER COLUMN base_url_id TYPE BIGINT,
    ALTER COLUMN basic_username_id TYPE BIGINT;

ALTER TABLE instances
    ALTER COLUMN name_id TYPE BIGINT,
    ALTER COLUMN host_id TYPE BIGINT,
    ALTER COLUMN username_id TYPE BIGINT,
    ALTER COLUMN basic_username_id TYPE BIGINT;

ALTER TABLE client_api_keys
    ALTER COLUMN client_name_id TYPE BIGINT;

ALTER TABLE instance_backup_runs
    ALTER COLUMN kind_id TYPE BIGINT,
    ALTER COLUMN status_id TYPE BIGINT,
    ALTER COLUMN requested_by_id TYPE BIGINT,
    ALTER COLUMN error_message_id TYPE BIGINT,
    ALTER COLUMN archive_path_id TYPE BIGINT,
    ALTER COLUMN manifest_path_id TYPE BIGINT;

ALTER TABLE instance_backup_items
    ALTER COLUMN torrent_hash_id TYPE BIGINT,
    ALTER COLUMN name_id TYPE BIGINT,
    ALTER COLUMN category_id TYPE BIGINT,
    ALTER COLUMN tags_id TYPE BIGINT,
    ALTER COLUMN archive_rel_path_id TYPE BIGINT,
    ALTER COLUMN infohash_v1_id TYPE BIGINT,
    ALTER COLUMN infohash_v2_id TYPE BIGINT,
    ALTER COLUMN torrent_blob_path_id TYPE BIGINT;

ALTER TABLE instance_errors
    ALTER COLUMN error_type_id TYPE BIGINT,
    ALTER COLUMN error_message_id TYPE BIGINT;

ALTER TABLE torrent_files_sync
    ALTER COLUMN torrent_hash_id TYPE BIGINT;

ALTER TABLE torznab_indexers
    ALTER COLUMN name_id TYPE BIGINT,
    ALTER COLUMN base_url_id TYPE BIGINT,
    ALTER COLUMN indexer_id_string_id TYPE BIGINT,
    ALTER COLUMN basic_username_id TYPE BIGINT;

ALTER TABLE torznab_indexer_capabilities
    ALTER COLUMN capability_type_id TYPE BIGINT;

ALTER TABLE torznab_indexer_categories
    ALTER COLUMN category_name_id TYPE BIGINT;

ALTER TABLE torznab_indexer_errors
    ALTER COLUMN error_message_id TYPE BIGINT;

CREATE VIEW api_keys_view AS
SELECT
    ak.id,
    ak.key_hash,
    sp.value AS name,
    ak.created_at,
    ak.last_used_at
FROM api_keys ak
INNER JOIN string_pool sp ON ak.name_id = sp.id;

CREATE VIEW arr_instances_view AS
SELECT
    ai.id,
    ai.type,
    sp_name.value AS name,
    sp_base_url.value AS base_url,
    sp_basic_user.value AS basic_username,
    ai.basic_password_encrypted,
    ai.api_key_encrypted,
    ai.enabled,
    ai.priority,
    ai.timeout_seconds,
    ai.last_test_at,
    ai.last_test_status,
    ai.last_test_error,
    ai.created_at,
    ai.updated_at
FROM arr_instances ai
INNER JOIN string_pool sp_name ON ai.name_id = sp_name.id
INNER JOIN string_pool sp_base_url ON ai.base_url_id = sp_base_url.id
LEFT JOIN string_pool sp_basic_user ON ai.basic_username_id = sp_basic_user.id;

CREATE VIEW client_api_keys_view AS
SELECT
    cak.id,
    cak.key_hash,
    sp.value AS client_name,
    cak.instance_id,
    cak.created_at,
    cak.last_used_at
FROM client_api_keys cak
INNER JOIN string_pool sp ON cak.client_name_id = sp.id;

CREATE VIEW instance_backup_items_view AS
SELECT
    ibi.id,
    ibi.run_id,
    sp_hash.value as torrent_hash,
    sp_name.value as name,
    sp_cat.value as category,
    ibi.size_bytes,
    sp_archive.value as archive_rel_path,
    sp_infohash_v1.value as infohash_v1,
    sp_infohash_v2.value as infohash_v2,
    sp_tags.value as tags,
    sp_blob.value as torrent_blob_path,
    ibi.created_at
FROM instance_backup_items ibi
LEFT JOIN string_pool sp_hash ON ibi.torrent_hash_id = sp_hash.id
LEFT JOIN string_pool sp_name ON ibi.name_id = sp_name.id
LEFT JOIN string_pool sp_cat ON ibi.category_id = sp_cat.id
LEFT JOIN string_pool sp_archive ON ibi.archive_rel_path_id = sp_archive.id
LEFT JOIN string_pool sp_infohash_v1 ON ibi.infohash_v1_id = sp_infohash_v1.id
LEFT JOIN string_pool sp_infohash_v2 ON ibi.infohash_v2_id = sp_infohash_v2.id
LEFT JOIN string_pool sp_tags ON ibi.tags_id = sp_tags.id
LEFT JOIN string_pool sp_blob ON ibi.torrent_blob_path_id = sp_blob.id;

CREATE VIEW instance_backup_runs_view AS
SELECT
    ibr.id,
    ibr.instance_id,
    sp_kind.value AS kind,
    sp_status.value AS status,
    sp_requested_by.value AS requested_by,
    ibr.requested_at,
    ibr.started_at,
    ibr.completed_at,
    sp_archive.value AS archive_path,
    sp_manifest.value AS manifest_path,
    ibr.total_bytes,
    ibr.torrent_count,
    ibr.category_counts_json,
    ibr.categories_json,
    ibr.tags_json,
    sp_error.value AS error_message
FROM instance_backup_runs ibr
JOIN string_pool sp_kind ON ibr.kind_id = sp_kind.id
JOIN string_pool sp_status ON ibr.status_id = sp_status.id
JOIN string_pool sp_requested_by ON ibr.requested_by_id = sp_requested_by.id
LEFT JOIN string_pool sp_error ON ibr.error_message_id = sp_error.id
LEFT JOIN string_pool sp_archive ON ibr.archive_path_id = sp_archive.id
LEFT JOIN string_pool sp_manifest ON ibr.manifest_path_id = sp_manifest.id;

CREATE VIEW instance_errors_view AS
SELECT
    ie.id,
    ie.instance_id,
    ie.error_type_id,
    sp_type.value AS error_type,
    ie.error_message_id,
    sp_message.value AS error_message,
    ie.occurred_at
FROM instance_errors ie
LEFT JOIN string_pool sp_type ON ie.error_type_id = sp_type.id
LEFT JOIN string_pool sp_message ON ie.error_message_id = sp_message.id;

CREATE VIEW instances_view AS
SELECT
    i.id,
    n.value AS name,
    h.value AS host,
    u.value AS username,
    i.password_encrypted,
    i.api_key_encrypted,
    bu.value AS basic_username,
    i.basic_password_encrypted,
    i.tls_skip_verify,
    i.sort_order,
    i.is_active,
    i.has_local_filesystem_access,
    i.use_hardlinks,
    i.hardlink_base_dir,
    i.hardlink_dir_preset,
    i.use_reflinks,
    i.fallback_to_regular_mode
FROM instances i
LEFT JOIN string_pool n ON i.name_id = n.id
LEFT JOIN string_pool h ON i.host_id = h.id
LEFT JOIN string_pool u ON i.username_id = u.id
LEFT JOIN string_pool bu ON i.basic_username_id = bu.id;

CREATE VIEW torrent_files_cache_view AS
SELECT
    tfc.id,
    tfc.instance_id,
    tfc.torrent_hash_id,
    sp_hash.value AS torrent_hash,
    tfc.file_index,
    tfc.name_id,
    sp_name.value AS name,
    tfc.size,
    tfc.progress,
    tfc.priority,
    tfc.is_seed,
    tfc.piece_range_start,
    tfc.piece_range_end,
    tfc.availability,
    tfc.cached_at
FROM torrent_files_cache tfc
LEFT JOIN string_pool sp_hash ON tfc.torrent_hash_id = sp_hash.id
LEFT JOIN string_pool sp_name ON tfc.name_id = sp_name.id;

CREATE VIEW torrent_files_sync_view AS
SELECT
    tfs.instance_id,
    tfs.torrent_hash_id,
    sp_hash.value AS torrent_hash,
    tfs.last_synced_at,
    tfs.torrent_progress,
    tfs.file_count
FROM torrent_files_sync tfs
LEFT JOIN string_pool sp_hash ON tfs.torrent_hash_id = sp_hash.id;

CREATE VIEW torznab_indexer_capabilities_view AS
SELECT
    tic.indexer_id,
    sp.value AS capability_type
FROM torznab_indexer_capabilities tic
INNER JOIN string_pool sp ON tic.capability_type_id = sp.id;

CREATE VIEW torznab_indexer_categories_view AS
SELECT
    tcat.indexer_id,
    tcat.category_id,
    sp.value AS category_name,
    tcat.parent_category_id
FROM torznab_indexer_categories tcat
INNER JOIN string_pool sp ON tcat.category_name_id = sp.id;

CREATE VIEW torznab_indexer_health AS
SELECT
    ti.id AS indexer_id,
    sp_name.value AS indexer_name,
    ti.enabled,
    ti.last_test_status,
    COALESCE(err_recent.error_count, 0) AS errors_last_24h,
    COALESCE(err_unresolved.unresolved_count, 0) AS unresolved_errors,
    lat.avg_latency_ms,
    lat.success_rate_pct,
    lat.total_requests AS requests_last_7d,
    lat.last_measured_at
FROM torznab_indexers ti
INNER JOIN string_pool sp_name ON ti.name_id = sp_name.id
LEFT JOIN (
    SELECT indexer_id, COUNT(*) AS error_count
    FROM torznab_indexer_errors
    WHERE occurred_at > CURRENT_TIMESTAMP - INTERVAL '1 day'
    GROUP BY indexer_id
) err_recent ON ti.id = err_recent.indexer_id
LEFT JOIN (
    SELECT indexer_id, COUNT(*) AS unresolved_count
    FROM torznab_indexer_errors
    WHERE resolved_at IS NULL
    GROUP BY indexer_id
) err_unresolved ON ti.id = err_unresolved.indexer_id
LEFT JOIN (
    SELECT
        indexer_id,
        AVG(CASE WHEN success = 1 THEN latency_ms ELSE NULL END) AS avg_latency_ms,
        CAST(SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) * 100 AS success_rate_pct,
        COUNT(*) AS total_requests,
        MAX(measured_at) AS last_measured_at
    FROM torznab_indexer_latency
    WHERE measured_at > CURRENT_TIMESTAMP - INTERVAL '7 days'
    GROUP BY indexer_id
) lat ON ti.id = lat.indexer_id;

CREATE VIEW torznab_indexers_view AS
SELECT
    ti.id,
    sp_name.value AS name,
    sp_base_url.value AS base_url,
    sp_indexer_id.value AS indexer_id,
    sp_basic_user.value AS basic_username,
    ti.basic_password_encrypted,
    ti.backend,
    ti.api_key_encrypted,
    ti.enabled,
    ti.priority,
    ti.timeout_seconds,
    ti.limit_default,
    ti.limit_max,
    ti.last_test_at,
    ti.last_test_status,
    ti.last_test_error,
    ti.created_at,
    ti.updated_at
FROM torznab_indexers ti
INNER JOIN string_pool sp_name ON ti.name_id = sp_name.id
INNER JOIN string_pool sp_base_url ON ti.base_url_id = sp_base_url.id
LEFT JOIN string_pool sp_indexer_id ON ti.indexer_id_string_id = sp_indexer_id.id
LEFT JOIN string_pool sp_basic_user ON ti.basic_username_id = sp_basic_user.id;
